version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    restart: always
    mem_limit: 400M
    mem_reservation: 200M
    cpus: 0.5